# Generated by Django 4.2.1 on 2023-06-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recipe_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_description',
            field=models.TextField(max_length=20),
        ),
    ]
